package.json

feat(): bump version

---

package.json
src/hooks/wallet/use-ledger-accounts.ts

fix(): add getServerSnapshot

---

package.json
src/components/atoms/number-input/styles.css.ts
src/pages/details/index.tsx

fix(): style fix

---

package.json
src/App.tsx
src/components/atoms/anchor/index.tsx
src/components/molecules/help-modal/index.tsx
src/components/molecules/help-modal/style.css.ts
src/hooks/use-geo-block.ts
src/index.package.ts
src/pages/position-details/index.tsx
src/pages/unstake-or-pending-action-review/index.tsx
src/providers/index.tsx
src/services/install-api-manager.ts
src/translation/English/translations.json
yarn.lock

feat(): new help modals

---

package.json
src/api/utils.ts
src/components/molecules/reward-token-details/index.tsx
src/domain/index.ts
src/domain/types/chains.ts
src/domain/types/wallet.ts
src/domain/types/yields.ts
src/hooks/api/opportunities/index.ts
src/hooks/use-staked-or-liquid-balance.ts
src/hooks/wallet/use-sk-wallet.ts
src/hooks/wallet/utils.ts
src/pages/details/components/select-opportunity.tsx
src/pages/details/hooks/use-details.ts
src/pages/details/index.tsx
src/pages/details/types.ts
src/pages/review/index.tsx
src/pages/steps/use-steps-machine.ts
src/providers/ledger/ledger-connector.ts
src/providers/misc/config.ts
src/providers/wagmi/index.ts
src/state/stake/index.tsx
src/vite-env.d.ts
yarn.lock

Feat: ledger near, 404 status fix, yields infinite load

---

package.json
src/domain/types/chains.ts
src/providers/cosmos/chains/index.ts
yarn.lock

- Coreum to supported networks

Enable Coreum

---

package.json
src/App.tsx
src/pages/details/components/footer.tsx
src/pages/details/hooks/use-details.ts
src/pages/details/hooks/use-footer-items.ts
src/providers/index.tsx
src/providers/wagmi/provider.tsx
src/translation/English/translations.json
src/types/purify-extend.d.ts
src/types/utils.ts
src/utils/extend-purify.ts

ENG-763: Extra yield info

---

package.json
src/services/local-storage.ts

fix(): ssr localStorage

---

build.ts
package.json

fix(): build

---

build.ts
package.json

chore(): remove dep inline

---

package.json
src/components/atoms/content-loader/index.tsx
src/pages/details/earn-page/components/footer.tsx
src/pages/details/earn-page/components/select-token-section/index.tsx
src/pages/details/earn-page/components/select-validator.tsx
src/pages/details/earn-page/components/select-yield-section/index.tsx
src/pages/details/positions-page/components/positions-list-item.tsx

fix(): content loader unique id

---

package.json
src/hooks/use-provider-details.ts
src/pages/complete/common.page.tsx
src/pages/complete/stake-complete.page.tsx
src/pages/complete/unstake-or-pending-action-complete.page.tsx
src/pages/complete/use-complete.hook.ts
src/state/stake/index.tsx

Fixes:
- https://linear.app/stakekit/issue/ENG-1004/available-balance-needs-to-be-grey-as-per-design-specs-not-red-should
- https://linear.app/stakekit/issue/ENG-1027/rocketpool-unstaking-wrong-info

Misc changes

---

package.json
src/hooks/api/use-multi-yields.ts

chore(): remove unused flag

---

package.json
src/components/atoms/select-modal/styles.css.ts
src/pages/details/earn-page/components/footer.tsx
src/pages/details/earn-page/hooks/use-footer-items.ts
src/translation/English/translations.json

fix(): text, animation

---

package.json
src/components/atoms/button/styles.css.ts
src/components/atoms/list/list-item.tsx
src/components/atoms/list/styles.css.ts
src/components/atoms/select-modal/index.tsx
src/components/atoms/select-modal/styles.css.ts
src/components/atoms/virtual-list/index.tsx
src/components/atoms/virtual-list/use-virtual-list-height.ts
src/components/molecules/header/header.tsx
src/hooks/use-estimated-rewards.ts
src/pages/complete/stake-complete.page.tsx
src/pages/details/earn-page/components/select-token-section/index.tsx
src/pages/details/earn-page/components/select-token-section/select-token.tsx
src/pages/details/earn-page/components/select-validator.tsx
src/pages/details/earn-page/components/select-yield-section/select-opportunity.tsx
src/pages/details/earn-page/earn.page.tsx
src/pages/details/earn-page/hooks/details-context.tsx
src/pages/details/earn-page/types.ts
src/pages/details/positions-page/components/import-validator.tsx
src/pages/details/positions-page/positions.page.tsx
src/pages/position-details/position-details.page.tsx
src/pages/review/use-review.hook.ts
src/providers/rainbow-kit.tsx
src/utils/index.ts

fix(): design

---

src/domain/types/chains.ts

- Optimism and Arbitrum chain configuration

Enable Optimism and Arbitrum

---

package.json
src/components/atoms/button/styles.css.ts
src/components/atoms/select-modal/index.tsx
src/components/molecules/help-modal/index.tsx
src/components/molecules/help-modal/style.css.ts
src/domain/types/yields.ts
src/pages/details/earn-page/components/select-yield-section/index.tsx
src/pages/details/earn-page/components/select-yield-section/select-opportunity.tsx
src/pages/details/positions-page/components/import-validator.tsx
src/pages/details/positions-page/components/styles.css.ts
src/pages/position-details/hooks/use-position-details.ts
src/pages/position-details/position-details.page.tsx
src/translation/English/translations.json
src/utils/index.ts

fix(): misc

---

package.json
src/pages/details/positions-page/positions.page.tsx

fix(): import val

---

.github/composite_actions/initial_setup/action.yml
.github/workflows/ci.yml
.github/workflows/publish-package.yml

chore(): workflow file changes

---

.github/composite_actions/initial_setup/action.yml
.github/workflows/ci.yml
.github/workflows/publish-package.yml
package.json
src/config/index.ts
src/hooks/api/use-multi-yields.ts
src/hooks/api/use-yield-opportunity.ts
src/hooks/use-logout.ts
src/pages/details/earn-page/hooks/details-context.tsx
src/state/stake/index.tsx
src/utils/either-async-pool.ts

chore(): minor changes

---

package.json
src/pages/complete/common.page.tsx
src/pages/review/use-review.hook.ts
src/pages/unstake-or-pending-action-review/use-unstake-or-pending-action-review.hook.ts
src/providers/ledger/ledger-connector.ts

fix(): gas fee token symbol

---

package.json
src/components/atoms/content-loader/index.tsx
src/components/atoms/content-loader/style.css.ts
src/pages/details/earn-page/components/footer.tsx
src/pages/details/earn-page/components/select-token-section/index.tsx
src/pages/details/earn-page/components/select-validator.tsx
src/pages/details/earn-page/components/select-yield-section/index.tsx
src/pages/details/positions-page/components/positions-list-item.tsx
yarn.lock

feat(): improve loading on ssr

---

src/domain/types/chains.ts

- Avalanche-c as possible EVM chain

chore: add avalanche-c support

---

package.json
src/components/atoms/image/index.tsx
src/components/atoms/number-input/index.tsx
src/components/atoms/token-icon/index.tsx
src/components/atoms/token-icon/style.css.ts
src/components/molecules/reward-token-details/index.tsx
src/pages/complete/common.page.tsx
src/pages/details/earn-page/components/select-validator.tsx
src/pages/details/earn-page/styles.css.ts
src/pages/details/positions-page/components/import-validator.tsx
src/pages/position-details/position-details.page.tsx

chore(): image comp revamp

---

package.json
src/pages/review/review.page.tsx
src/pages/review/use-review.hook.ts
src/pages/unstake-or-pending-action-review/use-unstake-or-pending-action-review.hook.ts
src/translation/English/translations.json

fix(): token symbol

---

package.json
src/pages/details/earn-page/components/footer.tsx
src/pages/details/earn-page/components/select-validator.tsx
src/pages/details/positions-page/components/fallback-content.tsx

fix(): button import

---

package.json
src/domain/index.ts
src/domain/types/chains.ts
src/providers/sk-wallet/index.tsx

fix(): add hwAppId for ledger EVM

---

package.json
src/components/atoms/content-loader/index.tsx
src/components/molecules/help-modal/index.tsx
src/hooks/tracking/use-track-event.ts
src/index.package.ts
src/main.tsx
src/pages/position-details/position-details.page.tsx
src/providers/index.tsx
src/providers/tracking/index.tsx

fix(): light theme

---

package.json
src/common/get-init-params.ts
src/domain/types/chains.ts
src/pages/details/earn-page/components/select-yield-section/select-opportunity-list-item.tsx
src/providers/ledger/ledger-connector.ts
src/state/stake/index.tsx

ENG-1158: ledger deep link

---

package.json
src/common/get-init-params.ts
src/utils/maybe-window.ts

fix(): window check

---

package.json
src/domain/index.ts
src/domain/types/tokens.ts
src/hooks/api/use-selected-stake-price.ts
src/hooks/use-position-balance-by-type.ts
src/pages/details/earn-page/state/details-context.tsx
src/pages/position-details/hooks/use-position-details.ts
src/pages/review/use-review.hook.ts
src/pages/unstake-or-pending-action-review/use-unstake-or-pending-action-review.hook.ts
src/state/stake/index.tsx

ENG-1190: prevent reset on complete

---

.env.example
package.json
src/config/index.ts
src/domain/index.ts
src/main.tsx
src/providers/cosmos/config.ts
src/providers/ethereum/config.ts
src/providers/ledger/ledger-connector.ts
src/providers/ledger/utils.ts
src/providers/settings.tsx
src/providers/wagmi/index.ts
src/services/install-api-manager.ts
src/styles/theme/global.css.ts
src/vite-env.d.ts
tests/index.test.tsx
tests/mocks/handlers.ts
tests/utils/test-utils.tsx

feat(): force walletconnect env

---

build.ts
package.json
src/config/index.ts
src/main.tsx
src/providers/location-transition/index.tsx
tests/index.test.tsx
tests/utils/test-utils.tsx

fix(): envs

---

src/pages/details/details-page/components/tabs.tsx
src/pages/details/details-page/details.page.tsx
src/pages/details/details-page/styles.css.ts
src/styles/tokens/colors.ts

ENG-1220: Animated tab border

---

src/pages/complete/stake-complete.page.tsx
src/pages/details/details-page/components/tabs.tsx
src/pages/details/details-page/styles.css.ts
src/pages/steps/common.page.tsx
src/pages/steps/stake-steps.page.tsx
src/pages/steps/use-steps-machine.hook.ts
src/pages/steps/use-steps.hook.ts
src/providers/index.tsx
src/providers/stake-history/index.tsx
src/state/stake/index.tsx

ENG-1255: Complete page amount fix

---

package.json

fix(): react-query-devtools as dep

---

package.json
src/pages/details/earn-page/state/details-context.tsx

fix(): show rest tokens

---

package.json
src/hooks/api/use-multi-yields.ts
src/pages/details/earn-page/state/details-context.tsx
src/pages/steps/hooks/use-steps.hook.ts
src/pages/steps/pages/common.page.tsx
src/pages/steps/pages/tx-state.tsx
src/translation/English/translations.json

ENG-1352,1353: Misc fixes

---

package.json
src/domain/types/chains.ts
src/providers/cosmos/chains/chain-registry.ts
src/providers/cosmos/chains/index.ts
yarn.lock

ENG-1470 - Add dYdX and Injective cosmos chains

---

package.json
src/hooks/use-estimated-rewards.ts
src/hooks/use-provider-details.ts
src/pages/details/earn-page/components/select-validator.tsx
src/pages/details/earn-page/components/select-yield-section/index.tsx
src/pages/details/earn-page/components/select-yield-section/select-opportunity-list-item.tsx
src/pages/details/earn-page/hooks/use-footer-items.ts
src/pages/details/earn-page/styles.css.ts
src/pages/details/positions-page/components/positions-list-item.tsx
src/pages/position-details/position-details.page.tsx
src/styles/tokens/colors.ts
src/translation/English/translations.json
src/utils/get-reward-rate.ts
src/utils/get-reward-type.ts
src/utils/index.ts
yarn.lock

ENG-1565,1437: Reward types

---

package.json
src/styles/theme/global.css.ts

fix(): hide scrollbar

---

package.json
src/hooks/api/use-default-tokens.ts
src/providers/cosmos/config.ts
src/providers/ethereum/config.ts

fix(): cosmos wallets init

---

package.json
src/pages/details/earn-page/state/details-context.tsx
src/pages/position-details/hooks/use-pending-actions.ts
src/pages/position-details/hooks/use-position-details.ts
src/pages/position-details/hooks/use-stake-exit-request-dto.ts
src/pages/unstake-or-pending-action-review/unstake-or-pending-action-review.page.tsx
src/state/unstake-or-pending-action/index.tsx
src/state/unstake-or-pending-action/types.ts

fix(): unstake navigation

---

src/App.tsx
src/hooks/navigation/use-details-match.ts
src/hooks/navigation/use-pending-action-match.ts
src/hooks/navigation/use-pending-action-select-validator-match.ts
src/hooks/navigation/use-unstake-match.ts
src/hooks/navigation/use-unstake-or-pending-action-match.ts
src/hooks/use-previous.ts
src/hooks/use-saved-ref.ts
src/state/unstake-or-pending-action/index.tsx
src/state/unstake-or-pending-action/types.ts
src/style.css.ts
src/styles/theme/global.css.ts

fix(): unstake provider unmount

---

src/components/molecules/referral-lock/index.tsx
src/components/molecules/referral-lock/style.css.ts

chore(): input referral grid

---

src/config/index.ts

fix(): remove unused env var

---

package.json
src/config/index.ts
src/main.tsx

chore(): remove unused env var

---

package.json
src/components/atoms/content-loader/index.tsx
src/components/atoms/select-modal/index.tsx
src/navigation/containers/animation-layout.tsx
src/pages/details/earn-page/components/select-yield-section/select-opportunity.tsx
src/providers/rainbow-kit.tsx
src/styles/theme/global.css.ts
src/styles/tokens/colors.ts
yarn.lock

feat(): style vars updates

---

package.json
src/components/atoms/select-modal/styles.css.ts
src/styles/theme/global.css.ts

fix(): style

---

package.json
src/common/delay-api-requests.ts
src/components/atoms/select-modal/styles.css.ts
src/navigation/containers/animation-layout.tsx
src/pages/details/earn-page/earn.page.tsx

feat(): delay api requests

---

package.json
src/App.tsx
src/main.tsx
src/navigation/containers/animation-layout.tsx
src/pages/components/footer-outlet/index.tsx
src/pages/details/details-page/components/tabs.tsx
src/pages/details/earn-page/components/select-yield-section/select-opportunity-list-item.tsx
src/pages/details/earn-page/earn.page.tsx
src/pages/details/earn-page/state/details-context.tsx
src/pages/details/positions-page/positions.page.tsx
src/providers/index.tsx
src/providers/mount-animation/index.tsx
src/providers/settings.tsx
tests/use-cases/referral-flow/setup.ts
tests/use-cases/staking-flow/setup.ts
yarn.lock

feat(): animation callback

---

package.json
src/components/molecules/help-modal/index.tsx
src/domain/types/yields.ts
src/translation/English/translations.json
yarn.lock

fix(): new yield type

---

package.json
src/pages/details/earn-page/hooks/use-footer-items.ts
src/translation/English/translations.json

fix(): add restake footer

---

build.ts
package.json
yarn.lock

fix(): extract all deps css

---

src/domain/types/chains.ts
src/pages/details/earn-page/components/select-token-section/index.tsx
src/pages/details/earn-page/state/details-context.tsx
src/pages/details/earn-page/state/types.ts
src/providers/ethereum/chains.ts
src/providers/ethereum/config.ts

feat(): viction staking

---

src/hooks/use-handle-deep-links.ts
src/pages/position-details/hooks/use-pending-actions.ts
src/state/unstake-or-pending-action/index.tsx

fix(): pending action navigation

---

package.json
src/hooks/use-handle-deep-links.ts
src/pages/position-details/hooks/use-pending-actions.ts
src/state/unstake-or-pending-action/index.tsx

Chore: bump version

---

package.json
src/App.tsx
src/navigation/containers/animation-layout.tsx
src/navigation/containers/styles.css.ts
src/style.css.ts

fix(): init layout

---

package.json
src/hooks/use-first-mount-state.ts

fix(): first mount hook

---

package.json
src/components/atoms/select-modal/styles.css.ts
src/components/molecules/select-validator/meta-info.tsx
src/components/molecules/select-validator/select-validator-list.tsx
src/components/molecules/select-validator/styles.css.ts
src/domain/types/external-providers.ts
src/translation/English/translations.json
src/utils/formatters.ts
src/utils/index.ts

feat(): add validator metadata

---

package.json
src/domain/types/external-providers.ts
src/domain/types/wallet.ts
src/domain/types/wallets/safe-wallet.ts
src/pages/steps/hooks/errors.ts
src/pages/steps/hooks/use-steps-machine.hook.ts
src/pages/steps/hooks/use-steps.hook.ts
src/providers/external-provider/index.ts
src/providers/settings.tsx
src/providers/sk-wallet/index.tsx
src/providers/sk-wallet/validation.ts
src/providers/wagmi/index.ts
yarn.lock

feat(): tx batch

---

package.json
src/domain/types/external-providers.ts
src/domain/types/wallets/safe-wallet.ts

chore(): naming

---

package.json
src/domain/types/external-providers.ts
src/domain/types/wallets/safe-wallet.ts
src/hooks/use-init-query-params.ts
src/providers/ledger/ledger-connector.ts
src/providers/sk-wallet/index.tsx

fix(): ll deeplink, safe changes

---

package.json
src/hooks/use-root-element.ts
src/pages/details/earn-page/components/select-token-section/select-token-list-item.tsx
src/pages/position-details/components/amount-block.tsx
src/translation/English/translations.json

Fix: copy updates, styles, rootElement

---

package.json
src/translation/English/errors.json
src/utils/errors.ts

feat(): update errors

---

package.json
src/components/molecules/select-validator/meta-info.tsx
src/pages/position-details/components/provider-details.tsx

fix(): address formating

---

README.md

feat(): update docs

---

package.json
src/components/atoms/list/list-item.tsx
src/components/atoms/token-icon/index.tsx
src/pages/details/earn-page/components/select-yield-section/index.tsx
src/pages/details/earn-page/state/details-context.tsx
src/pages/details/earn-page/state/types.ts
src/pages/details/positions-page/components/positions-list-item.tsx
src/pages/details/positions-page/components/styles.css.ts
src/pages/position-details/components/position-balances.tsx
src/translation/English/translations.json

feat(): reward points

---

build.ts
package.json

fix(): inline tslib

---

vite.config.ts

fix(): vite build

---

.husky/pre-commit
src/config/index.ts
src/providers/wagmi/index.ts

fix(): animation prevent block

---

.github/workflows/publish-package.yml
package.json
vite/vite.config.base.ts
yarn.lock

fix(): include buffer polyfill

---

package.json
src/components/atoms/list/styles.css.ts
src/components/molecules/header/header.tsx
src/pages/details/earn-page/components/select-token-section/index.tsx
src/pages/details/positions-page/components/positions-list-item.tsx
src/pages/details/positions-page/style.css.ts
src/styles/theme/properties.ts

feat(): zerion variant

---

package.json
src/components/molecules/chain-modal/index.tsx
src/components/molecules/header/header.tsx
src/pages/details/positions-page/positions.page.tsx

feat(): zerion - add chain switcher on positions

---

package.json
src/components/molecules/chain-modal/index.tsx
src/components/molecules/zerion-chain-modal/index.tsx
src/pages/details/earn-page/earn.page.tsx
src/pages/details/positions-page/positions.page.tsx
src/pages/position-details/hooks/use-position-details.ts

feat(): zerion style changes

---

package.json
src/hooks/use-yield-meta-info.ts
src/pages/details/earn-page/components/footer.tsx
src/pages/position-details/components/amount-block.tsx
src/pages/position-details/hooks/use-position-details.ts
src/pages/position-details/position-details.page.tsx
src/state/unstake-or-pending-action/index.tsx
src/state/unstake-or-pending-action/types.ts

ENG-2304, ENG-2305, ENG-2306: Multi input tokens footer copy fix

---

src/pages/complete/pages/stake-complete.page.tsx
src/pages/details/earn-page/state/details-context.tsx
src/pages/position-details/hooks/use-position-details.ts
src/pages/position-details/position-details.page.tsx
src/pages/review/hooks/use-unstake-or-pending-action-review.hook.ts
src/pages/review/pages/unstake-or-pending-action-review.page.tsx
src/pages/steps/pages/stake-steps.page.tsx
src/pages/steps/pages/unstake-or-pending-action-steps.page.tsx
src/translation/English/translations.json

ENG-2326, ENG-2325, ENG-2286: display token fix

---

src/pages/details/earn-page/components/footer.tsx
src/pages/details/earn-page/components/select-token-section/index.tsx
src/pages/details/earn-page/components/select-token-section/title.tsx
src/pages/details/earn-page/components/select-validator-section/index.tsx
src/pages/details/earn-page/components/select-yield-section/index.tsx
src/pages/details/earn-page/state/details-context.tsx
src/pages/details/earn-page/state/types.ts
src/pages/position-details/components/amount-block.tsx
src/pages/position-details/hooks/use-position-details.ts
src/pages/position-details/position-details.page.tsx
src/translation/English/translations.json

ENG-2283, ENG-1943, ENG-2256, ENG-2328: Copy updates

---

package.json
src/components/molecules/select-validator/meta-info.tsx
src/domain/index.ts
src/hooks/use-yield-meta-info.ts
src/pages/components/meta-info/index.tsx
src/pages/position-details/components/amount-block.tsx
src/pages/position-details/hooks/use-position-details.ts
src/pages/position-details/position-details.page.tsx
src/pages/steps/hooks/use-steps-machine.hook.ts
src/translation/English/translations.json
tests/use-cases/staking-flow/setup.ts
yarn.lock

ENG-2313: Luganodes handling 

---

package.json
src/domain/index.ts
src/domain/types/price.ts
src/translation/English/translations.json
src/utils/mappers.ts

ENG-2371, ENG-2370: Description + position price

---

package.json
src/components/atoms/number-input/index.tsx
src/components/atoms/number-input/styles.css.ts
src/components/molecules/global-modals/index.tsx
src/components/molecules/help-modal/index.tsx
src/navigation/containers/animation-layout.tsx
src/pages/components/footer-outlet/index.tsx
src/pages/details/details-page/components/tabs.tsx
src/pages/details/earn-page/components/select-token-section/index.tsx
src/pages/details/earn-page/earn.page.tsx
src/pages/details/earn-page/state/details-context.tsx
src/pages/position-details/components/amount-block.tsx
src/pages/position-details/hooks/use-position-details.ts
src/pages/position-details/position-details.page.tsx
src/providers/settings.tsx
src/state/stake/index.tsx
src/state/stake/types.ts
src/state/unstake-or-pending-action/index.tsx
src/state/unstake-or-pending-action/types.ts

feat(): close geo block, remove input limit, input error feedback

---

package.json
src/components/molecules/select-validator/index.tsx
src/pages/details/earn-page/components/select-token-section/select-token.tsx
src/pages/details/earn-page/components/select-validator-section/index.tsx
src/pages/details/earn-page/components/select-yield-section/select-yield-reward-details.tsx
src/pages/details/earn-page/state/details-context.tsx
src/pages/details/earn-page/state/types.ts
src/pages/position-details/position-details.page.tsx
src/providers/sk-wallet/index.tsx
src/state/stake/index.tsx

ENG-2378, ENG-2386: Validator search, close token reset, init token wait on loading

---

package.json
src/domain/types/stake.ts

fix(): default yield

---

package.json
src/assets/images/index.ts
src/components/molecules/help-modal/index.tsx
src/pages/details/earn-page/components/select-token-section/index.tsx
src/pages/details/earn-page/components/select-token-section/title.tsx
src/pages/details/earn-page/components/select-yield-section/index.tsx
src/pages/details/earn-page/components/select-yield-section/select-yield-reward-details.tsx
src/pages/position-details/components/provider-details.tsx
src/translation/English/translations.json

feat(): style changes

---

package.json
src/domain/index.ts
src/pages/steps/hooks/use-steps-machine.hook.ts

feat(): sign tx message

---

src/config/index.ts
src/providers/cosmos/wallet-manager.ts
tests/use-cases/deep-links-flow/setup.ts

fix(): tests

---

package.json
src/App.tsx
src/config/index.ts
src/pages/details/earn-page/components/footer/index.tsx
src/pages/details/earn-page/earn.page.tsx
src/pages/details/earn-page/state/earn-page-state-context.tsx
src/providers/index.tsx
src/providers/tracking/index.tsx
src/providers/tracking/tracking-variants.ts
yarn.lock

feat(): variant tracking

---

package.json
src/providers/index.tsx
src/providers/tracking/index.tsx

chore(): move tracking prop

---

package.json
src/providers/index.tsx
src/providers/tracking/index.tsx
src/providers/tracking/use-tracking-props.ts

fix(): tracking props

---

package.json
src/common/action-with-gas-estimate-and-check.ts
src/common/check-gas-amount.ts
src/hooks/api/use-pending-action-and-txs-construct.tsx
src/hooks/api/use-stake-enter-and-txs-construct.tsx
src/hooks/api/use-stake-exit-and-txs-construct.tsx
src/pages/details/earn-page/state/earn-page-context.tsx

ENG-2487: Insufficient gas warning

---

package.json
src/providers/wagmi/index.ts
src/utils/index.ts

feat(): mobile dapp auto connect

---

src/providers/wagmi/index.ts
src/utils/index.ts

fix(): mobile detect

---

src/pages/details/earn-page/state/earn-page-state-context.tsx
src/providers/wagmi/index.ts

fix(): wagmi autoconnect

---

package.json
src/domain/types/external-providers.ts
src/domain/types/wallets/generic-wallet.ts
src/domain/types/wallets/index.ts
src/providers/external-provider/index.ts
src/providers/sk-wallet/index.tsx
src/providers/sk-wallet/use-sync-external-provider.ts

refactor(): external provider

---

.vscode/settings.json
package.json
src/components/atoms/number-input/use-auto-resize-text.ts
src/components/atoms/token-icon/index.tsx
src/config/index.ts
src/domain/index.ts
src/hooks/use-variant-token-urls.ts
src/pages/details/details-page/components/tab.tsx
src/pages/details/earn-page/components/select-token-section/index.tsx
src/pages/details/earn-page/components/select-yield-section/staked-via.tsx
src/pages/details/earn-page/state/earn-page-context.tsx
src/pages/details/earn-page/state/types.ts
src/providers/settings.tsx
src/providers/tracking/use-tracking-props.ts

feat(): zerion ui updates

---

.vscode/settings.json
biome.json
package.json

chore(): update biome config

---

src/pages/position-details/hooks/use-stake-exit-request-dto.ts

Pass validator address on exit

Hotfix: Ethereum Staking aggregator fix

---

.vscode/settings.json
src/pages/components/footer-outlet/index.tsx
src/pages/steps/pages/common.page.tsx

Eng 2576 update styles for step machine

---

src/pages/details/positions-page/hooks/use-positions.ts

feat(): filter points from balance

---

tests/use-cases/renders-initial-page.test.tsx

test(): mocking initial load

---

.vscode/settings.json
package.json
src/providers/sk-wallet/index.tsx
src/providers/sk-wallet/use-init.ts
src/providers/wagmi/index.ts
tests/use-cases/deep-links-flow/deep-links-flow.test.tsx
tests/use-cases/deep-links-flow/setup.ts
tests/utils/mock-connector.ts
yarn.lock

ENG-2607: Init network support

---

tests/use-cases/renders-initial-page.test.tsx

fix(): removed unused mock

---

src/hooks/api/use-multi-yields.ts

feat(): filtered failed yields

---

.vscode/settings.json
src/components/atoms/virtual-list/index.tsx

feat(): increase virtual list viewport

---

packages/widget/package.json
packages/widget/src/App.tsx
packages/widget/src/components/molecules/help-modal/index.tsx
packages/widget/src/hooks/navigation/use-navigate-with-scroll-to-top.ts
packages/widget/src/pages/components/layout/index.tsx
packages/widget/src/pages/details/earn-page/state/earn-page-context.tsx
packages/widget/src/providers/root-element/index.tsx

fix(): help modals, navigate on scroll

---

package.json
packages/widget/package.json
packages/widget/src/pages/steps/hooks/use-steps.hook.ts
packages/widget/src/pages/steps/pages/common.page.tsx
packages/widget/src/pages/steps/pages/tx-state.tsx

fix(): after steps page animation

---

packages/widget/src/pages/details/details-page/details.page.tsx
packages/widget/src/pages/details/positions-page/components/positions-list-item.tsx
packages/widget/src/pages/details/positions-page/hooks/use-positions.ts

fix(): display proper name on position

---

packages/widget/src/pages/review/hooks/use-unstake-review.hook.ts

fix(): unstake steps navigation

---

package.json
packages/widget/src/pages/details/earn-page/components/select-token-section/index.tsx
yarn.lock

fix(): amount layout

---

packages/widget/src/pages/details/positions-page/components/positions-list-item.tsx

fix(): padding

---

packages/widget/src/pages/details/earn-page/components/select-token-section/index.tsx
packages/widget/src/pages/details/earn-page/components/select-token-section/styles.css.ts

fix(): token select layout

---

packages/widget/src/hooks/use-variant-token-urls.ts

fix(): checking symbol instead network for icons

---

packages/widget/package.json
packages/widget/src/hooks/use-gas-warning-check.ts
packages/widget/src/providers/api/api-client-provider.tsx
yarn.lock

feat(): bump rainbowkit

---

packages/widget/package.json
packages/widget/src/domain/types/chains.ts
packages/widget/src/providers/ethereum/config.ts
packages/widget/tests/use-cases/referral-flow/setup.ts
packages/widget/tests/use-cases/staking-flow/setup.ts
yarn.lock

feat: Add Base support to widget

---

packages/widget/src/translation/index.ts

fix(): language detection order

---

packages/widget/package.json
packages/widget/src/App.tsx
packages/widget/src/style.css.ts
yarn.lock

chore(): bump api hooks

---

packages/widget/package.json
packages/widget/src/hooks/use-reward-token-details/get-reward-token-symbols.tsx
packages/widget/src/pages/components/powered-by/index.tsx
packages/widget/src/providers/settings.tsx
packages/widget/src/translation/English/translations.json
packages/widget/src/translation/French/translations.json
packages/widget/src/translation/index.ts

feat(): language prop + update translations

---

packages/widget/src/components/molecules/global-modals/index.tsx

fix(): show geo block modal

---

packages/widget/tests/use-cases/geo-block.test.tsx

test(): geo block

---

packages/widget/src/pages/details/earn-page/state/utils.ts

feat(): init tron resource

---

packages/widget/package.json
packages/widget/src/hooks/use-handle-deep-links.ts
packages/widget/src/hooks/use-init-params.ts
packages/widget/src/hooks/use-init-query-params.ts
packages/widget/src/utils/formatters.ts
packages/widget/tests/use-cases/deep-links-flow/param-validation.test.ts
packages/widget/tests/use-cases/deep-links-flow/param-validation.test.tsx
packages/widget/tests/use-cases/deep-links-flow/setup.ts
packages/widget/tests/use-cases/deep-links-flow/utils.ts
packages/widget/tests/use-cases/staking-flow/staking-flow.test.tsx
yarn.lock

- Query param validation
- Position details deeplink
- Gas fee amount up to 10 decimals
- Fix flaky tests
https://github.com/stakekit/stakekit-monorepo/issues/1517

feat(): misc improvements/fixes

---

packages/widget/package.json
packages/widget/src/pages/review/hooks/use-pending-review.hook.ts
packages/widget/src/pages/review/hooks/use-stake-review.hook.ts
packages/widget/src/pages/review/hooks/use-unstake-review.hook.ts
packages/widget/src/pages/review/pages/common.page.tsx
packages/widget/src/pages/review/pages/pending-review.page.tsx
packages/widget/src/pages/review/pages/stake-review.page.tsx
packages/widget/src/pages/review/pages/unstake-review.page.tsx
packages/widget/src/translation/English/translations.json
packages/widget/src/translation/French/translations.json
packages/widget/src/utils/index.ts
packages/widget/tests/use-cases/staking-flow/setup.ts
yarn.lock

Eng 2848 display fee configuration in stake detail page

---

packages/widget/package.json
packages/widget/src/hooks/use-variant-token-urls.ts

fix(): variant urls

---

packages/widget/package.json
packages/widget/src/components/molecules/reward-token-details/index.tsx
packages/widget/src/pages/details/earn-page/components/select-yield-section/select-yield-reward-details.tsx
packages/widget/src/styles/theme/properties.ts

fix(): zerion morpho icon

---

packages/widget/src/pages/details/positions-page/components/positions-list-item.tsx
packages/widget/src/pages/details/positions-page/components/styles.css.ts
packages/widget/src/pages/details/positions-page/hooks/use-position-list-item.ts
packages/widget/src/pages/details/positions-page/hooks/use-positions.ts
packages/widget/src/pages/details/positions-page/style.css.ts
packages/widget/src/style.css.ts
packages/widget/src/styles/theme/properties.ts
packages/widget/src/styles/tokens/breakpoints.ts

fix(): positions responsive layout

---

packages/widget/src/components/atoms/icons/plus.tsx
packages/widget/src/components/atoms/max-button/index.ts
packages/widget/src/components/atoms/max-button/max-button.tsx
packages/widget/src/components/molecules/account-modal/index.tsx
packages/widget/src/components/molecules/chain-modal/index.tsx
packages/widget/src/pages/details/earn-page/components/select-token-section/index.tsx
packages/widget/src/pages/details/earn-page/components/select-validator-section/select-validator-trigger.tsx
packages/widget/src/pages/position-details/components/amount-block.tsx

feat(): data-rk and styles update

---

packages/widget/package.json

chore(): bump version

---

packages/widget/src/domain/types/yields.ts
packages/widget/src/hooks/use-yield-type.ts
packages/widget/src/pages/complete/pages/common.page.tsx
packages/widget/src/pages/details/earn-page/state/earn-page-context.tsx
packages/widget/src/pages/details/earn-page/types.ts
packages/widget/src/translation/English/translations.json
packages/widget/src/translation/French/translations.json

feat(): extended yield types

---

packages/widget/package.json
packages/widget/src/domain/types/yields.ts
packages/widget/src/pages/details/earn-page/state/earn-page-context.tsx
packages/widget/src/pages/details/earn-page/state/types.ts

fix(): grouping by yield type

---

packages/widget/src/components/molecules/reward-token-details/index.tsx

feat(): remove provider logo

---

packages/widget/package.json
packages/widget/src/pages/review/pages/common.page.tsx

feat(): fee configuration style changes

---

.changeset/eighty-toys-fly.md
packages/examples/with-nextjs/package.json
packages/widget/src/components/atoms/tooltip/index.tsx
packages/widget/src/pages/details/earn-page/components/select-yield-section/index.tsx
packages/widget/src/pages/review/hooks/use-fees.ts
packages/widget/src/pages/review/hooks/use-pending-review.hook.ts
packages/widget/src/pages/review/hooks/use-stake-review.hook.ts
packages/widget/src/pages/review/hooks/use-unstake-review.hook.ts
packages/widget/src/pages/review/pages/common.page.tsx
packages/widget/src/pages/review/pages/pending-review.page.tsx
packages/widget/src/pages/review/pages/stake-review.page.tsx
packages/widget/src/pages/review/pages/unstake-review.page.tsx
packages/widget/src/pages/review/types/index.ts
packages/widget/src/translation/English/translations.json
packages/widget/src/translation/French/translations.json
packages/widget/src/utils/index.ts

feat(): fees as percentage

---

.changeset/fluffy-onions-type.md
packages/widget/tests/use-cases/deep-links-flow/deep-links-flow.test.tsx
packages/widget/tests/use-cases/external-provider/external-provider.test.tsx
packages/widget/tests/use-cases/gas-warning-flow/gas-warning-flow.test.tsx
packages/widget/tests/use-cases/geo-block.test.tsx
packages/widget/tests/use-cases/referral-flow/referral-flow.test.tsx
packages/widget/tests/use-cases/renders-initial-page.test.tsx
packages/widget/tests/use-cases/select-opportunity.test.tsx
packages/widget/tests/use-cases/staking-flow/staking-flow.test.tsx

test(): unmount cleanup, fix flaky tests

---

.github/workflows/release.yml
package.json

ci(): update release

---

.changeset/tough-bottles-talk.md
packages/widget/src/providers/cosmos/chains/index.ts

fix(): add omony logo

---

.changeset/famous-tools-visit.md
packages/widget/src/pages/position-details/position-details.page.tsx

fix(): position details title center align

---

.changeset/few-rules-deliver.md
packages/widget/package.json
packages/widget/src/components/atoms/select-modal/index.tsx
packages/widget/src/components/atoms/tooltip/index.tsx
packages/widget/src/pages/components/meta-info/index.tsx
packages/widget/src/pages/components/meta-info/styles.css.ts
packages/widget/src/providers/rainbow-kit.tsx
packages/widget/src/providers/root-element/index.tsx
packages/widget/src/providers/theme-wrapper.tsx
packages/widget/src/styles/theme/contract.css.ts
packages/widget/src/styles/theme/global.css.ts
packages/widget/src/styles/theme/ids.ts
packages/widget/vite/vite.config.base.ts
yarn.lock

feat(): add global css layer

---

.changeset/lemon-coins-poke.md
packages/widget/src/components/atoms/button/styles.css.ts
packages/widget/src/styles/tokens/radii/contract.ts
packages/widget/src/styles/tokens/radii/values.ts

feat(): small button border radius

---

.changeset/soft-teachers-promise.md
packages/widget/src/hooks/use-init-query-params.ts
packages/widget/tests/use-cases/deep-links-flow/param-validation.test.tsx

- Update safe string codec and deep link param validation based on review

test(): update safe string codec

---

.changeset/slow-beans-protect.md
packages/widget/src/pages/details/earn-page/components/select-validator-section/select-validator-trigger.tsx
packages/widget/src/pages/details/earn-page/components/select-yield-section/staked-via.tsx
packages/widget/src/translation/English/translations.json
packages/widget/src/translation/French/translations.json

feat(): change validator label

---

.changeset/little-windows-switch.md
packages/widget/src/pages/details/details-page/components/tab.tsx
packages/widget/src/pages/details/details-page/components/tabs.tsx
packages/widget/src/pages/details/details-page/details.page.tsx
packages/widget/src/pages/details/details-page/styles.css.ts
packages/widget/src/pages/details/positions-page/components/positions-list-item.tsx
packages/widget/src/pages/details/positions-page/hooks/use-positions.ts
packages/widget/src/pages/details/shared/index.ts
packages/widget/src/translation/English/translations.json
packages/widget/src/translation/French/translations.json
packages/widget/tests/use-cases/referral-flow/referral-flow.test.tsx
packages/widget/tests/use-cases/renders-initial-page.test.tsx

Eng 2972 position tab update

---

.changeset/thirty-jeans-perform.md
packages/widget/src/pages/details/details-page/components/tab.tsx
packages/widget/src/pages/details/details-page/styles.css.ts

fix(): actions count badge position

---

.changeset/red-coins-exercise.md
packages/widget/src/hooks/use-init-query-params.ts

fix(): yieldId param validation

---

.changeset/good-roses-compare.md
packages/widget/src/providers/settings.tsx
packages/widget/src/providers/wagmi/index.ts

feat(): connectos mapper

---

.changeset/thirty-pumas-tickle.md
packages/widget/src/pages/details/earn-page/components/select-yield-section/staked-via.tsx

Feat/initial load UI improvement

---

.changeset/small-dancers-push.md
packages/widget/src/hooks/use-init-query-params.ts

feat(): init network from tokenString

---

.changeset/wicked-tools-scream.md
packages/widget/src/hooks/use-init-query-params.ts

fix(): token network param parsing

---

.changeset/hip-needles-sin.md
packages/widget/src/pages/details/activity-page/activity.page.tsx

Eng 3065 activity date label background color issue

---

.changeset/bright-crews-brake.md
packages/widget/package.json
packages/widget/src/domain/types/chains.ts
packages/widget/src/providers/cosmos/chains/get-chain-registry.ts
yarn.lock

- Support for Mantra Cosmos SDK chain

Feat: Enable Mantra Cosmos SDK chain

---

.changeset/silly-ducks-reply.md
packages/widget/src/providers/ethereum/config.ts

Fix: Core issues

---

.changeset/olive-walls-boil.md
packages/widget/src/providers/cosmos/chains/get-chain-registry.ts

- Wagmi name for Crypto Org POS chain

Feat: Update Crypto Org Wagmi name

---

.changeset/breezy-lizards-dress.md
packages/widget/src/domain/index.ts
packages/widget/src/domain/types/stake.ts
packages/widget/src/domain/types/yields.ts
packages/widget/src/hooks/use-max-min-yield-amount.ts
packages/widget/src/pages/details/earn-page/state/earn-page-context.tsx
packages/widget/src/pages/details/earn-page/state/earn-page-state-context.tsx
packages/widget/src/pages/details/earn-page/state/use-get-init-yield.ts
packages/widget/src/pages/details/earn-page/state/use-init-yield.ts
packages/widget/src/pages/details/earn-page/state/utils.ts
packages/widget/src/pages/position-details/state/index.tsx

fix(): init min amount

---

.changeset/thick-elephants-relax.md
packages/widget/src/hooks/use-provider-details.ts
packages/widget/src/pages/details/earn-page/state/earn-page-state-context.tsx

fix(): validator address fallback

---

.changeset/brave-bikes-guess.md
packages/widget/src/providers/rainbow-kit.tsx
packages/widget/vite/vite.config.package.ts

- Add body font to ConnectKit theme
- Expand external dependencies in Vite config for React runtime

feat(rainbow-kit): customize font and external dependencies

---

.changeset/clean-lies-smoke.md
packages/widget/package.json
packages/widget/src/domain/types/chains.ts
yarn.lock

feat(chains): add BSC support to Ledger wallet integration

---

.changeset/fresh-areas-go.md
packages/widget/src/providers/ledger/ledger-connector.ts

feat(ledger): enhance account handling in Ledger connector

---

.github/workflows/release.yml

fix(): release script

---

.changeset/giant-geckos-glow.md
packages/widget/src/common/delay-api-requests.ts

feat(): delay response instead of request

---

.changeset/quick-guests-make.md
packages/widget/src/pages/details/earn-page/state/earn-page-context.tsx
packages/widget/src/pages/details/earn-page/state/earn-page-state-context.tsx

feat(earn-page): enhance footer button registration logic

---

.changeset/tender-insects-fix.md
packages/widget/src/providers/settings.tsx

feat(widget): add customTranslations prop to extend translations

---

.changeset/wild-groups-swim.md
packages/widget/src/hooks/use-saved-ref.ts

fix(useSavedRef): save latest ref value before layout

---

.changeset/proud-hoops-repair.md
packages/widget/src/domain/types/chains.ts
packages/widget/src/providers/ledger/utils.ts

- Use correct Cronos currency from cosmos family

fix(ledger): cronos from cosmos family

---

.changeset/rare-pants-occur.md
packages/widget/src/hooks/use-init-query-params.ts

feat(initQueryParams): whitelist `+` in query params

---

.changeset/odd-buses-doubt.md
packages/widget/package.json
pnpm-lock.yaml

feat: bump Ledger Wallet API

---

.github/workflows/release.yml

ci: use gpg-key

---

.github/workflows/release.yml

ci: disable husky

---

.changeset/cool-foxes-beg.md
packages/widget/package.json
packages/widget/src/domain/types/chains/index.ts
packages/widget/src/domain/types/chains/substrate.ts
packages/widget/src/domain/types/transaction.ts
packages/widget/src/domain/types/wallets/generic-wallet.ts
packages/widget/src/pages/details/earn-page/state/use-stake-enter-request-dto.ts
packages/widget/src/pages/position-details/hooks/use-stake-exit-request-dto.ts
packages/widget/src/providers/sk-wallet/index.tsx
packages/widget/src/providers/substrate/config.ts
pnpm-lock.yaml

- Add Bittensor support for external provider

feat: add bittensor support

---

.changeset/afraid-rockets-peel.md
packages/widget/src/pages/details/earn-page/components/select-token-section/index.tsx
packages/widget/src/providers/settings.tsx

feat: enable usde banner prop

---

.changeset/early-bears-pay.md
packages/widget/src/hooks/use-yield-meta-info.tsx
packages/widget/src/pages/position-details/components/amount-block.tsx
packages/widget/src/translation/English/translations.json

fix: susd meta info

---

.changeset/grumpy-doodles-watch.md
packages/widget/src/domain/types/stake.ts
packages/widget/src/hooks/api/use-multi-yields.ts
packages/widget/src/pages/details/earn-page/state/use-init-token.ts
packages/widget/src/pages/details/earn-page/state/use-init-yield.ts
packages/widget/src/providers/settings/index.tsx
packages/widget/src/providers/settings/types.ts

feat: add preferred token yields per network support

---

.changeset/floppy-loops-glow.md
packages/widget/package.json
packages/widget/src/domain/types/stake.ts
packages/widget/src/domain/types/tokens.ts
packages/widget/src/hooks/use-estimated-rewards.ts
packages/widget/src/hooks/use-max-min-yield-amount.ts
packages/widget/src/pages/details/earn-page/components/select-yield-section/select-yield-reward-details.tsx
packages/widget/src/pages/details/earn-page/state/earn-page-context.tsx
packages/widget/src/pages/details/earn-page/state/types.ts
packages/widget/src/pages/position-details/hooks/use-position-details.ts
packages/widget/src/pages/position-details/state/index.tsx
packages/widget/src/pages/position-details/state/types.ts
pnpm-lock.yaml

feat: tao conversion

---

.changeset/free-houses-count.md
packages/widget/src/components/molecules/help-modal/index.tsx
packages/widget/src/pages/review/pages/action-review.page.tsx
packages/widget/src/pages/review/pages/common-page/common.page.tsx

fix: yield.xyz urls

---

.changeset/warm-books-yell.md
packages/widget/src/components/atoms/copy-text/index.tsx
packages/widget/src/components/molecules/select-validator/meta-info.tsx
packages/widget/src/components/molecules/select-validator/styles.css.ts
packages/widget/src/pages-dashboard/overview/positions/positions.page.tsx
packages/widget/src/pages-dashboard/overview/positions/styles.css.ts
packages/widget/src/pages-dashboard/position-details/components/provider-details.tsx
packages/widget/src/pages-dashboard/position-details/components/styles.css.ts
packages/widget/src/pages/details/earn-page/components/select-token-section/index.tsx
packages/widget/src/pages/details/earn-page/components/select-token-section/styles.css.ts
packages/widget/src/pages/position-details/components/provider-details.tsx
packages/widget/src/pages/position-details/styles.css.ts
packages/widget/src/utils/index.ts

This pull request introduces improvements to the widget's styling and refactors how validator addresses are displayed and copied, along with variant-based style support for several UI components. The main changes include enhanced copy-to-clipboard functionality, more flexible and maintainable styling using recipes and variants, and code cleanups for address display logic.
* Refactored the validator address display to use the `CopyText` component directly in `meta-info.tsx`, providing a more interactive and consistent copy-to-clipboard experience. Address formatting was also updated to show more characters.
* Removed redundant address-related styles and logic from provider details components and their stylesheets, simplifying the code and preventing duplication. Now, the address value from …

fix: styles
